add_newline = false

format = """\
  $username\
  $hostname\
  $directory\
  $git_branch\
  $ruby\
  $rust\
  $terraform\
  $line_break\
  $character\
  """

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[username]
show_always = true

[hostname]
ssh_only = false

[directory]
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = ""
