format = "$username$hostname$directory$git_branch$line_break$character"

[hostname]
ssh_only = false
format = "[$hostname](blue) in "

[username]
show_always = true
format = "[$user](blue) at "

[directory]
truncation_length = 0
truncate_to_repo = false
format = "[$path](blue)"

[git_status]
disabled = true

[git_branch]
symbol = ""
format = " on [$branch](blue)"
