format = "$username$directory$git_branch$line_break$character"

[hostname]
ssh_only = false
format = "[$hostname](blue)"

[username]
show_always = true
format = "[$user](blue) "

[directory]
truncation_length = 0
truncate_to_repo = false
format = "in [$path](blue)"

[git_status]
disabled = true

[git_branch]
symbol = ""
format = " on [$branch](blue)"
